services:

  backend:

    build:
      context: ./backend

    container_name: student-task-backend

    ports:
      - "3001:3001"

    restart: always


  frontend:

    build:
      context: ./frontend

    container_name: student-task-frontend

    ports:
      - "3000:80"

    depends_on:
      - backend

    restart: always